"""Shared paths and the check against paper/expected/ for the reproduce scripts."""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PAPER_DATA = ROOT / "data" / "paper"       # fetched by scripts/fetch_paper_data.py
GT = ROOT / "data" / "gt"
EXPECTED = ROOT / "paper" / "expected"
OUT = ROOT / "paper" / "out"

# The eight arms of the paper, as GT matrix stems in data/gt: OLMo/Qwen × DPO/SFT
# at 7–8B (the bare keys: OLMo-3-7B, Qwen3-8B) and at 30–32B (`_30b`:
# OLMo-3-32B, Qwen3-30B-A3B).
SCALES = [("7--8B", ""), ("30--32B", "_30b")]          # (block label, arm-key suffix)
BASE_ARMS = [("olmo", "dpo"), ("olmo", "sft"), ("qwen", "dpo"), ("qwen", "sft")]
ARMS_7B = [f"{f}_{m}" for f, m in BASE_ARMS]
ARMS_30B = [a + "_30b" for a in ARMS_7B]
ARMS = ARMS_7B + ARMS_30B
ARM_LABELS = {"olmo_dpo": "Olmo-7B DPO", "olmo_sft": "Olmo-7B SFT",
              "qwen_dpo": "Qwen-8B DPO", "qwen_sft": "Qwen-8B SFT",
              "olmo_dpo_30b": "Olmo-32B DPO", "olmo_sft_30b": "Olmo-32B SFT",
              "qwen_dpo_30b": "Qwen-30B DPO", "qwen_sft_30b": "Qwen-30B SFT"}
TARGETS = {
    "olmo_dpo": GT / "const_v3_dpo_full49_olmo3-caef4772a4ab/matrices/"
                     "const_v3_dpo_full49_olmo3_neutral_olmo-3_7b_likert",
    "olmo_sft": GT / "const_v3_sft_full66_olmo3-bb17778645f9/matrices/"
                     "const_v3_sft_full66_olmo3_olmo-3_7b_base_likert",
    "qwen_dpo": GT / "const_v3_dpo_full49-6b356df7db0a/matrices/"
                     "const_v3_dpo_full49_neutral_qwen3_8b_likert",
    "qwen_sft": GT / "const_v3_sft_full66-d9607bca37b2/matrices/"
                     "const_v3_sft_full66_qwen3_8b_base_likert",
    "olmo_dpo_30b": GT / "const_v3_dpo_full49_olmo3_32b-66f7857035ca/matrices/"
                         "const_v3_dpo_full49_olmo3_32b_neutral_olmo-3_32b_likert",
    "olmo_sft_30b": GT / "const_v3_sft_full66_olmo3_32b-7ec026a23d2a/matrices/"
                         "const_v3_sft_full66_olmo3_32b_olmo-3_32b_base_likert",
    "qwen_dpo_30b": GT / "const_v3_dpo_full49_qwen3_30b_a3b-54fbfe3f9393/matrices/"
                         "const_v3_dpo_full49_qwen3_30b_a3b_neutral_qwen3_30b_a3b_likert",
    "qwen_sft_30b": GT / "const_v3_sft_full66_qwen3_30b_a3b-3baa45ab00cb/matrices/"
                         "const_v3_sft_full66_qwen3_30b_a3b_qwen3_30b_a3b_base_likert",
}


def require_paper_data() -> None:
    if not (PAPER_DATA / "MANIFEST.json").exists():
        sys.exit(f"{PAPER_DATA} is missing; run: .venvs/core/bin/python scripts/fetch_paper_data.py")


def write(name: str, text: str) -> Path:
    OUT.mkdir(parents=True, exist_ok=True)
    p = OUT / name
    p.write_text(text)
    return p


def tabular_8x8(val: dict, fam: dict[str, str]) -> list[str]:
    """A symmetric arm × arm table as booktabs lines: scale blocks, then
    family, then method; the trivial diagonal is shown as ---."""
    n = len(BASE_ARMS)
    L = [r"\setlength{\tabcolsep}{4pt}",
         r"\begin{tabular}{ll" + "c" * len(ARMS) + "}",
         r"\toprule",
         " & & " + " & ".join(rf"\multicolumn{{{n}}}{{c}}{{{lab}}}" for lab, _ in SCALES) + r" \\",
         "".join(rf"\cmidrule(lr){{{3 + n * i}-{2 + n * (i + 1)}}}" for i in range(len(SCALES))),
         " & & " + " & ".join(rf"\multicolumn{{2}}{{c}}{{{fam[f]}}}"
                              for _ in SCALES for f in ("olmo", "qwen")) + r" \\",
         " & & " + " & ".join(m.upper() for _ in SCALES for _, m in BASE_ARMS) + r" \\"]
    for lab, suf in SCALES:
        L.append(r"\midrule")
        for i, (f, m) in enumerate(BASE_ARMS):
            a = f"{f}_{m}{suf}"
            cells = ["---" if a == b else f"{val[a][b]:.2f}" for b in ARMS]
            L.append(f"{lab if i == 0 else ''} & {fam[f]} {m.upper()} & "
                     + " & ".join(cells) + r" \\")
    return L + [r"\bottomrule", r"\end{tabular}"]


def _strip_comments(tex: str) -> list[str]:
    # Generated tables start with "% Auto-generated by ..." lines naming the
    # script that wrote them; those differ by design and are not compared.
    return [ln for ln in tex.splitlines() if not ln.lstrip().startswith("%")]


class Checker:
    """Collects mismatches between computed and expected values."""

    def __init__(self, name: str, rel_tol: float = 0.0, abs_tol: float = 1e-12):
        self.name, self.rel_tol, self.abs_tol = name, rel_tol, abs_tol
        self.failures: list[str] = []
        self.n = 0

    def value(self, path: str, got, want) -> None:
        if isinstance(want, dict):
            for k, w in want.items():
                if k not in got:
                    self.failures.append(f"{path}.{k}: missing")
                else:
                    self.value(f"{path}.{k}", got[k], w)
            return
        if isinstance(want, (list, tuple)):
            for i, w in enumerate(want):
                self.value(f"{path}[{i}]", got[i], w)
            return
        self.n += 1
        if isinstance(want, float) or isinstance(got, float):
            if want is None or got is None or not math.isclose(
                    got, want, rel_tol=self.rel_tol, abs_tol=self.abs_tol):
                self.failures.append(f"{path}: got {got!r}, expected {want!r}")
        elif got != want:
            self.failures.append(f"{path}: got {got!r}, expected {want!r}")

    def tex(self, out_name: str, expected_name: str) -> None:
        if not (EXPECTED / expected_name).exists():
            # A table whose typeset form is not frozen yet: written, not compared.
            print(f"  {out_name}: no expected/{expected_name} yet, not compared")
            return
        self.n += 1
        got = _strip_comments((OUT / out_name).read_text())
        want = _strip_comments((EXPECTED / expected_name).read_text())
        if got != want:
            diff = next((i for i, (a, b) in enumerate(zip(got, want)) if a != b),
                        min(len(got), len(want)))
            self.failures.append(f"{out_name}: differs from expected/{expected_name} "
                                 f"at line {diff + 1}")

    def finish(self) -> int:
        if self.failures:
            print(f"\n{self.name}: {len(self.failures)} of {self.n} checks FAILED")
            for f in self.failures:
                print("  " + f)
            return 1
        print(f"\n{self.name}: all {self.n} checks match the paper")
        return 0


def load_json(p: Path):
    return json.loads(Path(p).read_text())
