"""Appendix E: the ground-truth generalization matrices themselves.

Reproduces, from data/gt (the likert matrices of the eight arms: OLMo/Qwen ×
DPO/SFT at 7–8B and, keys suffixed `_30b`, at 30–32B):
  * the diagonal vs |off-diagonal| figure's numbers (diag_offdiag.json): mean
    ds-metric direct effect and transfer magnitude per arm, on the common 49×66
    frame and (SFT arms) the full 66×66 matrix, with 95% CIs from a 5000-draw
    bootstrap over trained tenets (seed 0);
  * tab:matrix-corr: off-diagonal Spearman ρ between the eight arms' matrices on
    the 49×66 frame;
  * the heatmaps' inputs, which are the GT matrices verbatim.

The figure inputs in paper/figures/appE_generalization_matrices/inputs/ are the
expected values: diag_offdiag.json byte-for-byte, the matrices byte-for-byte
against data/gt. The table is checked against paper/expected/appe/.

    .venvs/core/bin/python paper/reproduce/appe.py
"""

from __future__ import annotations

import json
import sys

import numpy as np

from _common import (ARMS, EXPECTED, OUT, ROOT, SCALES, TARGETS, Checker, load_json, tabular_8x8,
                     write)
from valuegen.analysis.correlate import offdiag_mask, reindex
from valuegen.analysis.steerability import load_target, offdiag_rho

FIG = ROOT / "paper/figures/appE_generalization_matrices/inputs"
N_BOOT, SEED = 5000, 0


def diag_offdiag_stats(m: np.ndarray, rows, cols) -> dict:
    off = offdiag_mask(rows, cols)
    diag = ~off
    assert (diag.sum(axis=1) == 1).all(), "every trained row needs its diagonal cell"
    # Per-row pieces, so the bootstrap can resample trained tenets.
    d_row = m[diag]
    o_sum = np.where(off, np.abs(m), 0).sum(axis=1)
    o_cnt = off.sum(axis=1)
    rng = np.random.default_rng(SEED)
    idx = rng.integers(0, len(rows), (N_BOOT, len(rows)))
    d_boot = d_row[idx].mean(axis=1)
    o_boot = o_sum[idx].sum(axis=1) / o_cnt[idx].sum(axis=1)
    return {"diag_mean": float(d_row.mean()),
            "diag_ci95": [float(v) for v in np.percentile(d_boot, [2.5, 97.5])],
            "offdiag_abs_mean": float(o_sum.sum() / o_cnt.sum()),
            "offdiag_abs_ci95": [float(v) for v in np.percentile(o_boot, [2.5, 97.5])],
            "n_diag": int(diag.sum()), "n_offdiag": int(off.sum())}


def diag_offdiag() -> dict:
    _, rows49, cols66 = load_target(TARGETS["qwen_dpo"])
    assert len(rows49) == 49 and len(cols66) == 66
    conds = []
    for _, suf in SCALES:
        for fam in ("olmo", "qwen"):
            conds += [(f"{fam}_dpo{suf}", f"{fam}_dpo{suf}", rows49),
                      (f"{fam}_sft{suf}_49x66", f"{fam}_sft{suf}", rows49),
                      (f"{fam}_sft{suf}_66x66", f"{fam}_sft{suf}", cols66)]
    out = {}
    for key, arm, rows in conds:
        m, r, c = load_target(TARGETS[arm])
        mm = reindex(m, r, c, rows, cols66)
        assert np.isfinite(mm).all(), key
        out[key] = diag_offdiag_stats(mm, rows, cols66)
    return out


def matrix_corr() -> dict:
    _, rows49, cols66 = load_target(TARGETS["qwen_dpo"])
    gt = {}
    for a in ARMS:
        m, r, c = load_target(TARGETS[a])
        gt[a] = reindex(m, r, c, rows49, cols66)
    return {a: {b: offdiag_rho(gt[a], gt[b], rows49, cols66) for b in ARMS} for a in ARMS}


def matrix_corr_tex(pair: dict) -> str:
    L = ["% Auto-generated by paper/reproduce/appe.py",
         r"\begin{table}[t]", r"\centering", r"\small"]
    L += tabular_8x8(pair, {"olmo": "Olmo", "qwen": "Qwen"})
    L += [r"\caption{Off-diagonal Spearman $\rho$ between the full generalization "
          r"matrices of each finetuning experiment. Matrix structure is similar "
          r"across both cross-model and cross-finetuning method comparisons, "
          r"suggesting some shared internal structure in how models represent "
          r"values.}",
          r"\label{tab:matrix-corr}", r"\end{table}"]
    return "\n".join(L) + "\n"


def main() -> int:
    chk = Checker("Appendix E")

    # Heatmap inputs are the GT matrices verbatim.
    for a in ARMS:
        for suf in ("_raw.npy", "_normalized.npy", "_raw_values.json"):
            chk.n += 1
            src = TARGETS[a].parent / (TARGETS[a].name + suf)
            if (FIG / f"{a}_likert{suf}").read_bytes() != src.read_bytes():
                chk.failures.append(f"inputs/{a}_likert{suf}: differs from {src.relative_to(ROOT)}")

    do = diag_offdiag()
    write("appe_diag_offdiag.json", json.dumps(do, indent=2))
    chk.n += 1
    if (OUT / "appe_diag_offdiag.json").read_bytes() != (FIG / "diag_offdiag.json").read_bytes():
        chk.failures.append("appe_diag_offdiag.json: differs from the figure's inputs/diag_offdiag.json")

    pair = matrix_corr()
    write("appe_matrix_corr.json", json.dumps(pair, indent=2) + "\n")
    chk.value("matrix_corr", pair, load_json(EXPECTED / "appe" / "matrix_corr.json"))
    write("appe_matrix_corr_table.tex", matrix_corr_tex(pair))
    chk.tex("appe_matrix_corr_table.tex", "appe/matrix_corr_table.tex")
    return chk.finish()


if __name__ == "__main__":
    sys.exit(main())
