"""Appendix H: which value representation clusters best, under which method?

For the two neutral-SFT 7B models (Qwen3-8B, OLMo-3-7B), each of the five RQ1
value representations (Persona, Gradient, Weight, Behavior-Embd,
Description-Embd) is clustered with UPGMA, k-medoids and k-means on 2D
nonmetric MDS, for k = 2..8. Each partition is scored by its silhouette's z
against 2000 size-preserving relabelings of that same partition (seed 0).

Reproduces, from data/paper/rq1/grids/{qwen,olmo}_dpo (Description-Embd: the
66-value v3 grid in data/paper/apph):
  * every (model, representation) curves.csv, against paper/expected/apph/curves/;
  * tab:rq2_clustering_z (z averaged over k, then over the two models);
  * the value-embedding-comp figure's input (k-medoids z vs k, model-averaged),
    against paper/figures/appH_clustering_methods/inputs/.
All comparisons are byte-for-byte. Exit status 1 on any mismatch.

    .venvs/core/bin/python paper/reproduce/apph.py     # ~5 min on one CPU
"""

from __future__ import annotations

import csv
import io
import json
import sys
import warnings

import numpy as np

from _common import EXPECTED, OUT, PAPER_DATA, ROOT, Checker, require_paper_data, write
from valuegen.analysis import cluster as CL
from valuegen.analysis import mds as M
from valuegen.analysis.steerability import load_values

GRIDS = PAPER_DATA / "rq1" / "grids"
FIG_INPUT = ROOT / "paper/figures/appH_clustering_methods/inputs/value-embedding-comp.json"
MODELS = {"qwen3_8b": "qwen_dpo", "olmo3_7b": "olmo_dpo"}
# representation -> grid file stem (Description-Embd is the 66-value v3 grid)
REPS = {
    "persona": "persona",
    "grad_proj": "grad_proj",
    "weight_steer": "weight_steer",
    "sent_emb_behavior": "sentemb_behavior",
    "sent_emb_desc": None,
}
METHODS = ["upgma", "kmedoids", "mds"]
KS = list(range(2, 9))
N_RAND = 2000

REP_ORDER = ["persona", "grad_proj", "weight_steer", "sent_emb_behavior", "sent_emb_desc"]
REP_LABELS = {
    "persona": r"\textsc{Persona}",
    "grad_proj": r"\textsc{Gradient}",
    "weight_steer": r"\textsc{Weight}",
    "sent_emb_behavior": r"\textsc{Behavior-Embd}",
    "sent_emb_desc": r"\textsc{Description-Embd}",
}
METHOD_LABELS = {"upgma": "UPGMA", "kmedoids": "k-medoids", "mds": "MDS"}


def load_grid(model: str, rep: str):
    if REPS[rep] is None:
        stem = PAPER_DATA / "apph" / "sentence_emb_v3"
    else:
        stem = GRIDS / MODELS[model] / REPS[rep]
    rows, _ = load_values(f"{stem}_values.json")
    return M.drop_nan_values(np.load(f"{stem}.npy"), rows)


def curves_csv(model: str, rep: str) -> str:
    """The clustering curves of one (model, representation), as curves.csv text."""
    sim, _ = load_grid(model, rep)
    dist = M.cos_to_dist(sim)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", FutureWarning)
        coords, _ = M.mds_variant(sim, "nonmetric")
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["method", "k", "silhouette", "z", "gamma", "null_mean", "null_sd", "sizes"])
    for m in METHODS:
        for k in KS:
            lab = CL.cluster_labels(dist, k, m, coords=coords)
            mu, sd = CL.relabel_null_stats(dist, lab, n_rand=N_RAND)
            sc = CL.score_partition(dist, lab, mu, sd)
            sizes = "/".join(map(str, sorted(np.bincount(lab).tolist())))
            w.writerow([m, k, f"{sc['silhouette']:.4f}", f"{sc['z']:.3f}", f"{sc['gamma']:.4f}",
                        f"{mu:.4f}", f"{sd:.4f}", sizes])
    return buf.getvalue()


def parse_z(text: str) -> dict[str, list[float]]:
    """{method: [z per k]} from curves.csv text (the table reads the rounded z)."""
    out: dict[str, list[float]] = {}
    for r in csv.DictReader(io.StringIO(text)):
        out.setdefault(r["method"], []).append(float(r["z"]))
    return out


def z_table(z) -> str:
    def cell(rep, m):
        return float(np.mean([np.mean(z[(model, rep)][m]) for model in MODELS]))

    def unique_best(vals):
        best = max(vals)
        return None if sum(f"{v:.1f}" == f"{best:.1f}" for v in vals) > 1 else best

    grid = {(rep, m): cell(rep, m) for rep in REP_ORDER for m in METHODS}
    overall = unique_best(list(grid.values()))
    col_best = {m: unique_best([grid[(rep, m)] for rep in REP_ORDER]) for m in METHODS}
    L = ["% Auto-generated by paper/reproduce/apph.py",
         r"\begin{table}[t]", r"\centering", r"\small",
         r"\begin{tabular}{l" + "c" * len(METHODS) + "}", r"\toprule",
         " & ".join([""] + [METHOD_LABELS[m] for m in METHODS]) + r" \\", r"\midrule"]
    for rep in REP_ORDER:
        cells = []
        for m in METHODS:
            v = grid[(rep, m)]
            s = f"{v:.1f}"
            if overall is not None and v == overall:
                s = r"\textbf{" + s + "}"
            elif col_best[m] is not None and v == col_best[m]:
                s = r"\textit{" + s + "}"
            cells.append(s)
        L.append(REP_LABELS[rep] + " & " + " & ".join(cells) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}",
          r"\caption{Average $z$-scores from $k=2$ to $k=8$, for each combination "
          r"of clustering method and value embedding method. Bold denotes the best "
          r"overall combination (persona vectors \& k-medoids), which we use to "
          r"create \taxonomyname; \textit{italics} denotes the best embedding "
          r"method for a fixed clustering method.}",
          r"\label{tab:rq2_clustering_z}", r"\end{table}"]
    return "\n".join(L) + "\n"


def embedding_comp(z) -> str:
    """The figure input: model-averaged k-medoids z per k, per representation."""
    curves = {rep: dict(k=KS, z=[float(np.mean([z[(m, rep)]["kmedoids"][i] for m in MODELS]))
                                 for i in range(len(KS))])
              for rep in ["persona", "grad_proj", "sent_emb_behavior", "sent_emb_desc", "weight_steer"]}
    return json.dumps(dict(models=list(MODELS), method="kmedoids",
                           note="model-averaged, size-preserving null", curves=curves), indent=1)


def main() -> int:
    require_paper_data()
    chk = Checker("Appendix H")
    z = {}
    for model in MODELS:
        for rep in REPS:
            name = f"{model}_{rep}.csv"
            text = curves_csv(model, rep)
            write(f"apph_curves_{name}", text)
            chk.n += 1
            if text.encode() != (EXPECTED / "apph" / "curves" / name).read_bytes():
                chk.failures.append(f"curves {name}: differs from expected/apph/curves/{name}")
            z[(model, rep)] = parse_z(text)
            print(f"  {model}/{rep}: clustered", flush=True)

    write("apph_z_table.tex", z_table(z))
    chk.tex("apph_z_table.tex", "apph/z_table.tex")
    comp = embedding_comp(z)
    write("apph_value-embedding-comp.json", comp)
    chk.n += 1
    if comp.encode() != FIG_INPUT.read_bytes():
        chk.failures.append("value-embedding-comp.json: differs from the figure input")
    return chk.finish()


if __name__ == "__main__":
    sys.exit(main())
