"""RQ1: do cheap predictors recover the generalization matrix?

Reproduces, from data/gt (the GT matrices) and data/paper/rq1 (predictor grids):
  * tab:rq1_predictors — off-diagonal Spearman ρ of each predictor grid vs. each
    arm's ds-metric GT matrix on the common 49×66 frame, the cross-arm aggregate
    with a joint row bootstrap (5000 resamples, seed 0), and the symmetric
    ceiling row;
  * tab:value-space-corr — Mantel ρ between the eight arms' persona grids
    (2000 joint permutations, seed 0).

The arms are OLMo/Qwen × DPO/SFT at 7–8B and at 30–32B. Each is scored with
the grid of the model its training *starts from*: the neutral-SFT model for DPO
arms, the pretrained base (urial0 scaffold, self-generated pairs) for SFT arms.
Persona/Gradient use layer 18 (Qwen3-8B) and 16 (OLMo-3-7B), picked by a layer
sweep that never sees the GT; the 30–32B models were not swept and read the
layer at the same relative depth (24 of 48, 32 of 64).

Writes paper/out/rq1.json and the two .tex tables, then checks every number
against paper/expected/. Exit status 1 on any mismatch.

    .venvs/core/bin/python paper/reproduce/rq1.py
"""

from __future__ import annotations

import itertools
import json
import sys

import numpy as np

from _common import (ARMS, BASE_ARMS, EXPECTED, PAPER_DATA, SCALES, TARGETS, Checker, load_json,
                     require_paper_data, tabular_8x8, write)
from valuegen.analysis.correlate import offdiag_mask, reindex
from valuegen.analysis.steerability import (aggregate_bootstrap, load_target, load_values,
                                            mantel, offdiag_rho, symmetric_ceiling)

GRIDS = PAPER_DATA / "rq1" / "grids"
# Table row order; the bootstrap is drawn per resample, not per predictor, so
# order does not affect any number.
PREDICTORS = ["sentence_emb", "sentemb_behavior", "persona", "grad_proj", "weight_steer"]
PRED_LABELS = {
    "sentence_emb": r"\textsc{Description-Embd}",
    "sentemb_behavior": r"\textsc{Behavior-Embd}",
    "weight_steer": r"\textsc{Weight}",
    "persona": r"\textsc{Persona}",
    "grad_proj": r"\textsc{Gradient}",
}
FAM = {"olmo": "Olmo3", "qwen": "Qwen3"}
N_BOOT, N_PERM, SEED = 5000, 2000, 0


def load_grid(arm: str, pred: str):
    m = np.load(GRIDS / arm / f"{pred}.npy")
    rows, cols = load_values(GRIDS / arm / f"{pred}_values.json")
    return m, rows, cols


def predictor_table():
    # The common frame: the 49 DPO-trained tenets × the 66 evaluated tenets.
    _, rows49, cols66 = load_target(TARGETS["qwen_dpo"])
    assert len(rows49) == 49 and len(cols66) == 66
    gt = {}
    for a in ARMS:
        m, r, c = load_target(TARGETS[a])
        gt[a] = reindex(m, r, c, rows49, cols66)
    off = offdiag_mask(rows49, cols66)

    preds, rho = {}, {p: {} for p in PREDICTORS}
    for a in ARMS:
        for p in PREDICTORS:
            m, r, c = load_grid(a, p)
            preds[(p, a)] = reindex(m, r, c, rows49, cols66)
            rho[p][a] = offdiag_rho(gt[a], preds[(p, a)], rows49, cols66)
    point, ci, n_arms = aggregate_bootstrap(gt, preds, off, PREDICTORS, ARMS,
                                            n_boot=N_BOOT, seed=SEED)
    ceiling = {a: symmetric_ceiling(gt[a], rows49, cols66) for a in ARMS}
    ceiling["aggregate"] = float(np.mean([ceiling[a] for a in ARMS]))
    aggregate = {p: {"mean_rho": point[p], "ci95": list(ci[p]), "n_arms": n_arms[p]}
                 for p in PREDICTORS}
    return {"predictor_rho": rho, "aggregate": aggregate, "symmetric_ceiling": ceiling}


def _unique_best(vals):
    """The max, only if it is the unique winner at 2-decimal display."""
    vals = [v for v in vals if v is not None]
    if not vals:
        return None
    best = max(vals)
    if sum(1 for v in vals if f"{v:.2f}" == f"{best:.2f}") > 1:
        return None
    return best


def predictor_tex(res) -> str:
    per, agg, ceil = res["predictor_rho"], res["aggregate"], res["symmetric_ceiling"]
    best_arm = {a: _unique_best([per[p][a] for p in PREDICTORS]) for a in ARMS}
    # The aggregate column bolds every predictor tied at the displayed max.
    best_agg = max(f"{agg[p]['mean_rho']:.2f}" for p in PREDICTORS)
    n = len(BASE_ARMS)
    L = ["% Auto-generated by paper/reproduce/rq1.py",
         r"\begin{table}[t]", r"\centering", r"\small",
         r"\setlength{\tabcolsep}{4pt}",
         r"\begin{tabular}{l|" + ("c" * n + "|") * len(SCALES) + "c}", r"\toprule",
         " & " + " & ".join(rf"\multicolumn{{{n}}}{{c|}}{{{lab}}}" for lab, _ in SCALES) + r" & \\",
         " & " + " & ".join(rf"\multicolumn{{2}}{{c{'|' if f == 'qwen' else ''}}}{{{FAM[f]}}}"
                            for _ in SCALES for f in ("olmo", "qwen")) + r" & \\",
         " & " + " & ".join(m.upper() for _ in SCALES for _, m in BASE_ARMS)
         + r" & \textbf{Aggregate} \\",
         r"\midrule",
         r"\textit{Ceiling} & " + " & ".join(f"{ceil[a]:.2f}" for a in ARMS)
         + f" & {ceil['aggregate']:.2f}" + r" \\",
         r"\midrule"]
    for p in PREDICTORS:
        cells = []
        for a in ARMS:
            v = per[p][a]
            s = f"{v:.2f}"
            if best_arm[a] is not None and v == best_arm[a]:
                s = r"\textbf{" + s + "}"
            cells.append(s)
        a = agg[p]
        half = (a["ci95"][1] - a["ci95"][0]) / 2
        mean_s = f"{a['mean_rho']:.2f}"
        if mean_s == best_agg:
            mean_s = r"\textbf{" + mean_s + "}"
        agg_s = f"{mean_s}\\,{{\\scriptsize$\\pm\\,{half:.2f}$}}"
        if a["n_arms"] != len(ARMS):
            agg_s += f" {{\\scriptsize({a['n_arms']} arms)}}"
        L.append(PRED_LABELS[p] + " & " + " & ".join(cells) + " & " + agg_s + r" \\")
    L += [r"\bottomrule", r"\end{tabular}",
          r"\caption{Off-diagonal Spearman $\rho$ between each predictor's "
          r"similarity grid and the ground-truth generalization matrix $G$ for "
          r"each combination of model and training method. $\pm$ denotes 95\% "
          r"confidence intervals, computed by bootstrapping. Representations are "
          r"computed on the same base model that was trained unless explicitly "
          r"stated otherwise in \Cref{sec:embeddings}. The ceiling is computed by "
          r"correlating each matrix $G$ with a symmetrized version of itself, "
          r"which establishes a ceiling on how well $G$ can be predicted with a "
          r"symmetric similarity matrix.}",
          r"\label{tab:rq1_predictors}", r"\end{table}"]
    return "\n".join(L) + "\n"


def value_space():
    rng = np.random.default_rng(SEED)
    sims, values = {}, None
    for a in ARMS:
        m, rows, _ = load_grid(a, "persona")
        if values is None:
            values = rows
        idx = [rows.index(v) for v in values]
        m = m[np.ix_(idx, idx)]
        assert np.isfinite(m).all(), a
        sims[a] = m
    dist = {a: 1.0 - sims[a] for a in ARMS}
    rho = {a: {a: 1.0} for a in ARMS}
    p = {}
    for a, b in itertools.combinations(ARMS, 2):
        r, pv = mantel(dist[a], dist[b], rng, n_perm=N_PERM)
        rho[a][b] = rho[b][a] = r
        p[f"{a}_vs_{b}"] = pv
    return {"mantel_rho": rho, "p": p, "n_values": len(values), "nperm": N_PERM}


def value_space_tex(vs) -> str:
    rho = vs["mantel_rho"]
    L = ["% Auto-generated by paper/reproduce/rq1.py",
         r"\begin{table}[t]", r"\centering", r"\small"]
    L += tabular_8x8(rho, {"olmo": "Olmo", "qwen": "Qwen"})
    L += [r"\caption{Spearman $\rho$ between the persona-vector similarity matrices of "
          r"each base model. Similarity matrices are highly correlated across models, "
          r"providing preliminary evidence for a shared latent space of values.}",
          r"\label{tab:value-space-corr}", r"\end{table}"]
    return "\n".join(L) + "\n"


def main() -> int:
    require_paper_data()
    res = predictor_table()
    res["value_space"] = value_space()
    write("rq1.json", json.dumps(res, indent=1) + "\n")
    write("rq1_predictor_table.tex", predictor_tex(res))
    write("rq1_value_space_corr_table.tex", value_space_tex(res["value_space"]))

    chk = Checker("RQ1")
    chk.value("rq1", res, load_json(EXPECTED / "rq1.json"))
    chk.tex("rq1_predictor_table.tex", "rq1_predictor_table.tex")
    chk.tex("rq1_value_space_corr_table.tex", "rq1_value_space_corr_table.tex")
    return chk.finish()


if __name__ == "__main__":
    sys.exit(main())
